services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accidents
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio-crash
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: myminioadmin
      MINIO_ROOT_PASSWORD: mysecurepassword
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  data_loader:
    build: .
    container_name: data_loader
    restart: on-failure
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/accidents
    volumes:
      - ./data:/app/data
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["python", "/app/insert_data.py"]

volumes:
  pgdata:
  minio_data:

